//
// Created by Fabian Uni on 15/07/2024.
//

#ifndef SAMPLETOY_ESP32_ARDUINO_SAMPLETOYRUNTIMECONTROLS_H
#define SAMPLETOY_ESP32_ARDUINO_SAMPLETOYRUNTIMECONTROLS_H

#endif //SAMPLETOY_ESP32_ARDUINO_SAMPLETOYRUNTIMECONTROLS_H
